-keepattributes LineNumberTable,SourceFile
-renamesourcefileattribute SourceFile
-keep class com.google.android.** { *; }
-keep class retrofit2.** {*;}
-keep class org.slf4j.** {*;}
-keep class okhttp3.** {*;}
-keep interface retrofit2.** {*;}
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**